# Tests for use_fyi_md()

# Create temp file
tmp <- tempfile(fileext = ".md")
on.exit(unlink(tmp), add = TRUE)

# Test basic functionality
result <- use_fyi_md("stats", path = tmp)
expect_equal(result, tmp)
expect_true(file.exists(tmp))

# Check header is present
content <- readLines(tmp)
expect_true(any(grepl("Generated by fyi::use_fyi_md", content)))
expect_true(any(grepl("Regenerate with:", content)))

# Check content structure
expect_true(any(grepl("# fyi: stats", content)))
expect_true(any(grepl("## Exported Functions", content)))

# Test append mode
tmp2 <- tempfile(fileext = ".md")
on.exit(unlink(tmp2), add = TRUE)

use_fyi_md("stats", path = tmp2)
use_fyi_md("tools", path = tmp2, append = TRUE)

content2 <- paste(readLines(tmp2), collapse = "\n")
# Should have separator
expect_true(grepl("---", content2))
# Should have both packages
expect_true(grepl("fyi: stats", content2))
expect_true(grepl("fyi: tools", content2))
